using System;
using System.Collections.Generic;

namespace SpellingGame2
{
    class Program
    {
        static void Main(string[] args) {
            IUserInterface userInterface = new UI();
            userInterface.OptionSelected += delegate (object sender, InterfaceEventArgs e) { return; };
            userInterface.GetInput();
            userInterface.WriteIntoDescription("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris molestie risus ligula, ac vehicula felis ultricies vel. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce egestas, erat sed tempus ullamcorper, mi nunc auctor augue, sit amet condimentum nulla justo in nulla. Sed eleifend finibus metus, eget sodales augue vehicula placerat. In nec odio dolor. Cras varius eros vitae ex rhoncus tempus. Suspendisse malesuada id tellus a tristique. Nullam mauris elit, ullamcorper id ante sit amet, tristique venenatis libero. Quisque ornare blandit ligula, sed tempus arcu bibendum eu. Quisque lectus turpis, ornare eget vulputate eget, faucibus quis dolor.", ConsoleColor.Red, ConsoleColor.Black, true);
            userInterface.WriteIntoDescription("Curabitur tincidunt sem a metus aliquet accumsan. Quisque consequat nisl ut diam consectetur, at ullamcorper velit faucibus. Integer sit amet sapien viverra, interdum velit in, interdum nisi. Duis feugiat molestie dui, non condimentum risus luctus non. Vestibulum eget vestibulum nibh, at bibendum lectus. Donec placerat neque et ipsum tristique posuere. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tincidunt erat et nisi faucibus ornare. Aliquam nulla elit, imperdiet commodo magna vitae, aliquam condimentum mauris. Maecenas finibus dolor nisl, sed consectetur sapien laoreet laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque non dui ut dui feugiat tempor ac sed nibh. Aenean lacinia egestas leo in feugiat. Nunc id ligula nisi. Nunc vulputate tincidunt finibus.", true);
            userInterface.WriteIntoDescription("Curabitur eu malesuada eros. Vestibulum scelerisque condimentum orci ornare gravida. Nulla facilisi. Nunc in commodo justo. Sed quis dui aliquam, finibus felis id, volutpat urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tempor aliquam eros, vel sodales odio fermentum quis. Sed luctus interdum nisl, in laoreet erat. Donec massa magna, aliquam vitae nunc at, ornare efficitur ipsum. Proin quam nisl, pulvinar at erat venenatis, posuere ultrices mi", true);
            userInterface.WriteIntoDescription("Aliquam scelerisque elit eu tortor sollicitudin, nec efficitur velit imperdiet. Sed vestibulum tincidunt dui, et imperdiet lorem.Suspendisse vestibulum nunc lectus, quis auctor tortor posuere sed. Vestibulum eu diam nulla. Mauris at ante id neque consectetur fringilla.Integer placerat hendrerit metus, ac tempus justo pharetra a. Ut luctus mi nulla, eu fringilla eros egestas sit amet. Donec sodales euismod dolor, non maximus nisi faucibus non. Sed sodales eros a lectus hendrerit sollicitudin.", true);
            userInterface.WriteIntoDescription("Sed convallis urna erat, at porta arcu venenatis non. Phasellus feugiat sollicitudin tempus. Vivamus efficitur dui vel turpis condimentum consectetur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla interdum lectus vel dictum rutrum. Fusce luctus metus nec semper fringilla.Morbi at eros nisi. Mauris ut turpis ornare dui sodales accumsan et quis turpis.Nunc malesuada, neque non suscipit ultricies, lectus sapien varius erat, in placerat lectus libero in nulla. Mauris sagittis dolor sit amet augue interdum ullamcorper.", true);
            userInterface.WriteIntoDescription("Quisque scelerisque risus mauris, eu tincidunt massa vulputate at. Aenean lacus eros, iaculis vestibulum condimentum vel, placerat ut orci. Duis egestas nec quam eget rhoncus. Donec sed odio tempor nulla sodales tempor. Nunc dui libero, dignissim quis nibh eget, luctus egestas massa. Sed sollicitudin facilisis maximus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec condimentum eleifend odio, id ullamcorper sapien varius vulputate. Sed at accumsan ligula, ac semper nibh. Donec in eros placerat, varius mauris sed, pretium nibh. Vestibulum eu nulla posuere, volutpat arcu ut, tincidunt diam. Donec nibh diam, egestas ut tellus a, fermentum ornare dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec ut velit mauris.", true);
            userInterface.WriteIntoDescription("Sed vitae facilisis turpis. Suspendisse volutpat, augue sit amet pharetra tincidunt, leo justo varius tortor, non laoreet orci enim a eros. Suspendisse neque est, ultrices a risus ac, volutpat convallis magna. Integer sed porttitor leo, vitae pretium purus. Quisque accumsan dictum aliquet. Sed vehicula tellus non dapibus laoreet. Mauris nec vehicula tortor, eget luctus nisi. Etiam ac convallis enim.", true);
            userInterface.WriteIntoDescription("Maecenas molestie mi a neque congue ullamcorper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed tellus turpis, mattis sed varius at, commodo sit amet magna. Aliquam erat volutpat. Quisque congue felis turpis, a fermentum velit laoreet id. Quisque pretium erat vel justo gravida, et fringilla nulla vulputate. Donec et tortor ac sem feugiat pellentesque vitae ut justo. Aliquam placerat augue quis erat pretium, viverra placerat enim fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer rhoncus quis lectus quis cursus. In pretium commodo neque a tempus.", false);
            Console.ReadKey(true);
        }
    }
}
